version: 2

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - id: nrseg-darwin
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/nrseg/main.go
  - id: nrseg-linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/nrseg/main.go
  - id: nrseg-windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    main: ./cmd/nrseg/main.go

archives:
  - format: "tar.gz"
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md
checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: nrseg
    url_template: "https://github.com/budougumi0617/nrseg/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    repository:
      owner: budougumi0617
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: "github-actions[bot]"
      email: "github-actions[bot]@users.noreply.github.com"
    homepage: "https://github.com/budougumi0617/nrseg"
    description: "Insert function segments into any function/method for Newrelic APM."
    license: "MIT"
    install: |
      bin.install "nrseg"
    test: |
      system "#{bin}/nrseg -h"
